/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import dal.ModuloConexao;
import java.awt.Color;
import java.sql.*;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.text.MaskFormatter;
/**
 *
 * @author MICRO
 */
public class TelaIndex extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void nomeusuario(){
        
        String usuario = lblUsuario.getText();
        TelaCadUsuario.lblUsuario2.setText(usuario);
        if(lblUsuario.getForeground().equals(Color.red)){
            TelaCadUsuario.lblUsuario2.setForeground(Color.red);
        }else{            
        }
    }
    /**
     * Creates new form TelaIndex
     */
    public TelaIndex() {
        initComponents();
        conexao = ModuloConexao.conector();
        MaskFormatter telefoneMask;
        MaskFormatter dataMask;
        txtClienteCpf.setFormatterFactory(null);
        try {
            MaskFormatter cpfMask = new MaskFormatter("###.###.###-##");
            cpfMask.setPlaceholderCharacter(' ');
            cpfMask.install(txtClienteCpf);            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
        try {
            telefoneMask = new MaskFormatter("(##) #####-####");
            telefoneMask.setPlaceholderCharacter(' ');
            telefoneMask.install(txtClienteTelzap);
            telefoneMask.install(txtClienteTeleme);
        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Erro formatter");
        }
        try {
            dataMask = new MaskFormatter("##/##/####");
            dataMask.setPlaceholderCharacter(' ');
            dataMask.install(txtClienteDataven);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtClienteRua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClienteBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtClienteNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        txtClienteDataven = new javax.swing.JFormattedTextField();
        txtClienteCpf = new javax.swing.JFormattedTextField();
        btnLimpar = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtClienteTelzap = new javax.swing.JFormattedTextField();
        txtClienteTeleme = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTabela2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadCli = new javax.swing.JMenuItem();
        menCadUsu = new javax.swing.JMenuItem();
        menAju = new javax.swing.JMenu();
        menAjuSob = new javax.swing.JMenuItem();
        menOp = new javax.swing.JMenu();
        menOpSair = new javax.swing.JMenuItem();
        MenOpLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProjetoAcademia");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Logo.jpg"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblUsuario.setText("Usuário");
        lblUsuario.setToolTipText("");

        lblData.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblData.setText("UsuárioAtual:");

        tbTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTabela.setRowHeight(26);
        tbTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTabela);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtClienteRua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtClienteRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteRuaActionPerformed(evt);
            }
        });
        jPanel1.add(txtClienteRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 190, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        txtClienteBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtClienteBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 190, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Bairro:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("TelefoneZap: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("TelefoneEmergencia:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Rua:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Nome:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtClienteNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtClienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtClienteNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 190, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Data Vencimento:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        txtClienteDataven.setColumns(10);
        txtClienteDataven.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtClienteDataven.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClienteDatavenFocusGained(evt);
            }
        });
        jPanel1.add(txtClienteDataven, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 150, 30));

        try {
            txtClienteCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtClienteCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClienteCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClienteCpfFocusLost(evt);
            }
        });
        jPanel1.add(txtClienteCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 190, 30));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        jPanel1.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 140, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Pesquisa:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        try {
            txtClienteTelzap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtClienteTelzap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClienteTelzapFocusGained(evt);
            }
        });
        jPanel1.add(txtClienteTelzap, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 150, 30));

        try {
            txtClienteTeleme.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtClienteTeleme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClienteTelemeFocusGained(evt);
            }
        });
        jPanel1.add(txtClienteTeleme, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 150, 30));

        tbTabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbTabela2);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Clientes Proximos a Data de Vencimento");

        menCad.setText("Cadastro");
        menCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadActionPerformed(evt);
            }
        });

        menCadCli.setText("Cliente");
        menCad.add(menCadCli);

        menCadUsu.setText("Usuarios");
        menCadUsu.setEnabled(false);
        menCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuActionPerformed(evt);
            }
        });
        menCad.add(menCadUsu);

        Menu.add(menCad);

        menAju.setText("Ajuda");

        menAjuSob.setText("Sobre");
        menAjuSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAjuSobActionPerformed(evt);
            }
        });
        menAju.add(menAjuSob);

        Menu.add(menAju);

        menOp.setText("Opçoes");
        menOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpActionPerformed(evt);
            }
        });

        menOpSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menOpSair.setText("Sair");
        menOpSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpSairActionPerformed(evt);
            }
        });
        menOp.add(menOpSair);

        MenOpLogout.setText("Deslogar");
        MenOpLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpLogoutActionPerformed(evt);
            }
        });
        menOp.add(MenOpLogout);

        Menu.add(menOp);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblData)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 46, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(40, 40, 40))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblUsuario)
                                        .addGap(98, 98, 98))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(lblData)
                        .addGap(12, 12, 12)
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        setSize(new java.awt.Dimension(1100, 850));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menAjuSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAjuSobActionPerformed
        // TODO add your handling code here:
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_menAjuSobActionPerformed

    private void menCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuActionPerformed
        // TODO add your handling code here:        
        TelaCadUsuario usuario = new TelaCadUsuario();
        usuario.setVisible(true);
        nomeusuario();
        this.dispose();
        
        
    }//GEN-LAST:event_menCadUsuActionPerformed

    private void txtClienteRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteRuaActionPerformed

    private void txtClienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteNomeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        PreparedStatement pst2 = null;
        ResultSet rs2 = null;
        String sql = "SELECT CPF, Nome, TelefoneZap, TelefoneEme, Rua, Bairro, DATE_FORMAT(DataVencimento, '%d/%m/%Y') AS DataVencimentoFormatada FROM clientes;";
        try {
            pst = conexao.prepareStatement(sql, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = pst.executeQuery();
            rs.last();
            int row=rs.getRow();
            int col=rs.getMetaData().getColumnCount();
            rs.beforeFirst();
            String rowData[][]=new String[row][col];            
            int r=0;            
            while(rs.next()){
                for(int i=0;i<col;i++){                    
                    rowData[r][i] = rs.getString(i+1);
                
                }                
                r++;
            }
            String[] NomeColuna={"CPF","Nome","TelefoneZap","TelefoneEme","Rua","Bairro","DataVencimento"};
            DefaultTableModel model = (DefaultTableModel)tbTabela.getModel();
            model.setDataVector(rowData, NomeColuna);
            model.fireTableDataChanged();            
        } catch (Exception e) {
            System.out.println(e);
        }
        String sql2 = "SELECT CPF, Nome, DATE_FORMAT(DataVencimento, '%d/%m/%Y') AS DataVencimentoFormatada FROM clientes WHERE DataVencimento BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 1 DAY);";
        try {
            pst2 = conexao.prepareStatement(sql2, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs2 = pst2.executeQuery();
            rs2.last();
            int row=rs2.getRow();
            int col=rs2.getMetaData().getColumnCount();
            rs2.beforeFirst();
            String rowData[][]=new String[row][col];            
            int r=0;            
            while(rs2.next()){
                for(int i=0;i<col;i++){                    
                    rowData[r][i] = rs2.getString(i+1);
                
                }                
                r++;
            }
            String[] NomeColuna={"CPF","Nome","DataVencimento"};
            DefaultTableModel model = (DefaultTableModel)tbTabela2.getModel();
            model.setDataVector(rowData, NomeColuna);
            model.fireTableDataChanged();            
        } catch (Exception e) {
            System.out.println(e);
        }

        
    }//GEN-LAST:event_formWindowOpened

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        Date data = null;
        String txtdata = txtClienteDataven.getText();
        String Cpfv = txtClienteCpf.getText();
        String nome = txtClienteNome.getText();
        String telefoneZap = txtClienteTelzap.getText();
        String telefoneEme = txtClienteTeleme.getText();
        String rua = txtClienteRua.getText();
        String bairro = txtClienteBairro.getText();        
        if (Cpfv.isEmpty() || nome.isEmpty() || telefoneZap.isEmpty() || telefoneEme.isEmpty() || rua.isEmpty() || bairro.isEmpty() || txtdata.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Cpfv = Cpfv.replaceAll("[^0-9]", "");
            if(Cpfv.length() != 11){
                JOptionPane.showMessageDialog(this,"Erro, Tente de novo","Erro",JOptionPane.ERROR_MESSAGE);
                return;
            }else{                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Erro CPF");
            e.printStackTrace();
        }
        try {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                data = sdf.parse(txtdata);            
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(this, "Formato de data inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dataFormatada = dateFormat.format(data);        
        
            boolean b = pst.execute("INSERT INTO clientes (CPF, Nome, TelefoneZap, TelefoneEme, Rua, Bairro, DataVencimento) VALUES ('" + txtClienteCpf.getText() + "', '" + txtClienteNome.getText() + "', '" + txtClienteTelzap.getText() + "', '" + txtClienteTeleme.getText() + "', '" + txtClienteRua.getText() + "', '" + txtClienteBairro.getText() + "', '" + dataFormatada + "')");
            if(!b){
                JOptionPane.showMessageDialog(this,"CADASTRADO");
            }else{
                JOptionPane.showMessageDialog(this,"Erro, Tente de novo");
            }
            formWindowOpened(null);
            txtClienteCpf.setText(null);
            txtClienteNome.setText(null);
            txtClienteTelzap.setText(null);
            txtClienteTeleme.setText(null);
            txtClienteRua.setText(null);
            txtClienteBairro.setText(null);
            txtClienteDataven.setText(null);
        }catch(SQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(this,"CPF Ja cadastrado");
            e.printStackTrace();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this,e);
            e.printStackTrace();        
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void tbTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTabelaMouseClicked
        // TODO add your handling code here:
        String cpf = tbTabela.getValueAt(tbTabela.getSelectedRow(), 0).toString();
        Date data = null;        
        try {
            String sql = "SELECT CPF, Nome, TelefoneZap, TelefoneEme, Rua, Bairro, DATE_FORMAT(DataVencimento, '%d/%m/%Y') AS DataVencimentoFormatada FROM clientes WHERE CPF='"+cpf+"'";
            rs = pst.executeQuery(sql);
            while(rs.next()){
                txtClienteCpf.setText(rs.getString("CPF"));
                txtClienteNome.setText(rs.getString("Nome"));
                txtClienteTelzap.setText(rs.getString("TelefoneZap"));
                txtClienteTeleme.setText(rs.getString("TelefoneEme"));
                txtClienteRua.setText(rs.getString("Rua"));
                txtClienteBairro.setText(rs.getString("Bairro"));
                txtClienteDataven.setText(rs.getString("DataVencimentoFormatada"));
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbTabelaMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        tbTabela.clearSelection();
        txtClienteCpf.setText(null);
        txtClienteNome.setText(null);
        txtClienteTelzap.setText(null);
        txtClienteTeleme.setText(null);
        txtClienteRua.setText(null);
        txtClienteBairro.setText(null);
        txtClienteDataven.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        String cpf = tbTabela.getValueAt(tbTabela.getSelectedRow(), 0).toString();
        try {            
            int r = JOptionPane.showConfirmDialog(this, "Voce tem certeza de Deletar esse Cliente de CPF:"+cpf+"?","Confirmaçao",JOptionPane.YES_NO_OPTION);
            if(r==0){
                if(!pst.execute("DELETE FROM clientes WHERE CPF='"+cpf+"'")){
                    formWindowOpened(null);
                    txtClienteCpf.setText(null);
                    txtClienteNome.setText(null);
                    txtClienteTelzap.setText(null);
                    txtClienteTeleme.setText(null);
                    txtClienteRua.setText(null);
                    txtClienteBairro.setText(null);
                    txtClienteDataven.setText(null);
                }
            }else{                
                txtClienteCpf.setText(null);
                txtClienteNome.setText(null);
                txtClienteTelzap.setText(null);
                txtClienteTeleme.setText(null);
                txtClienteRua.setText(null);
                txtClienteBairro.setText(null);
                txtClienteDataven.setText(null);
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        String cpf = tbTabela.getValueAt(tbTabela.getSelectedRow(), 0).toString();
        Date data = null;
        String txtdata = txtClienteDataven.getText();        
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            data = sdf.parse(txtdata);            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Formato de data inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dataFormatada = dateFormat.format(data);        
        
        try {
            boolean b = pst.execute("UPDATE clientes set Nome='" + txtClienteNome.getText() + "', TelefoneZap='" + txtClienteTelzap.getText() + "', TelefoneEme='" + txtClienteTeleme.getText() + "', Rua='" + txtClienteRua.getText() + "', Bairro='" + txtClienteBairro.getText() + "', DataVencimento='" + dataFormatada + "' WHERE CPF='" + txtClienteCpf.getText() + "'");
            formWindowOpened(null);
            if(!b){
                JOptionPane.showMessageDialog(this,"Editado");
            }else{
                JOptionPane.showMessageDialog(this,"Erro, Tente de novo");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:
        
        try {
            String sql = "SELECT * FROM clientes WHERE Nome LIKE '%"+txtPesquisa.getText()+"%'";
            pst = conexao.prepareStatement(sql, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = pst.executeQuery();
            rs.last();
            int row=rs.getRow();
            int col=rs.getMetaData().getColumnCount();
            String rowData[][]=new String[row][col];
            rs.beforeFirst();
            int r=0;
            while(rs.next()){
                for(int i=0;i<col;i++){
                    rowData[r][i] = rs.getString(i+1);
                }
                r++;
            }
            String[] NomeColuna={"CPF","Nome","TelefoneZap","TelefoneEme","Rua","Bairro","DataVencimento"};
            DefaultTableModel model = (DefaultTableModel)tbTabela.getModel();
            model.setDataVector(rowData, NomeColuna);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void menCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadActionPerformed

    private void menOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_menOpActionPerformed

    private void menOpSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpSairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?");
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_menOpSairActionPerformed

    private void txtClienteCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteCpfFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtClienteCpfFocusLost

    private void txtClienteCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteCpfFocusGained
        // TODO add your handling code here:
        String cpf = txtClienteCpf.getText();       
        if (cpf.matches("\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}")) {
        } else {
            txtClienteCpf.setText("");
        }
    }//GEN-LAST:event_txtClienteCpfFocusGained

    private void txtClienteDatavenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteDatavenFocusGained
        // TODO add your handling code here:
        String data = txtClienteDataven.getText();        
        if (data.matches("\\d{2}/\\d{2}/\\d{4}")) {
        } else {
            txtClienteDataven.setText("");
        }
    }//GEN-LAST:event_txtClienteDatavenFocusGained

    private void txtClienteTelemeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteTelemeFocusGained
        // TODO add your handling code here:
        String telefone = txtClienteTeleme.getText();      
        if (telefone.matches("\\(\\d{2}\\) \\d{5}-\\d{4}")) {            
        } else {           
            txtClienteTeleme.setText("");
        }
    }//GEN-LAST:event_txtClienteTelemeFocusGained

    private void txtClienteTelzapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteTelzapFocusGained
        // TODO add your handling code here:
        String telefone = txtClienteTelzap.getText();      
        if (telefone.matches("\\(\\d{2}\\) \\d{5}-\\d{4}")) {            
        } else {           
            txtClienteTelzap.setText("");
        }
    }//GEN-LAST:event_txtClienteTelzapFocusGained

    private void MenOpLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpLogoutActionPerformed
        // TODO add your handling code here:
        Tela tela = new Tela();
        tela.setVisible(true);
        this.dispose();
        try {
            conexao.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_MenOpLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                TelaIndex tela = new TelaIndex();
                tela.setVisible(true);                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenOpLogout;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menAju;
    private javax.swing.JMenuItem menAjuSob;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCadCli;
    public static javax.swing.JMenuItem menCadUsu;
    private javax.swing.JMenu menOp;
    private javax.swing.JMenuItem menOpSair;
    private javax.swing.JTable tbTabela;
    private javax.swing.JTable tbTabela2;
    private javax.swing.JTextField txtClienteBairro;
    private javax.swing.JFormattedTextField txtClienteCpf;
    private javax.swing.JFormattedTextField txtClienteDataven;
    private javax.swing.JTextField txtClienteNome;
    private javax.swing.JTextField txtClienteRua;
    private javax.swing.JFormattedTextField txtClienteTeleme;
    private javax.swing.JFormattedTextField txtClienteTelzap;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
